---
# tasks file for roles/nginx
- name: get current nginx version
  shell: nginx -v
  register: nginx_current_ver
  ignore_errors: True
  changed_when: False


- name: include install.yml when first install nginx service or not found spefified nginx version
  include: install.yml
  when: nginx_version not in nginx_current_ver.stderr or nginx_first_install

- name: include configure.yml
  include: configure.yml

- name: include service.yml
  include: service.yml
